CREATE TABLE `users` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(50) CHARACTER SET latin1 NOT NULL,
  `email` varchar(100) CHARACTER SET latin1 NOT NULL,
  `password` varchar(100) CHARACTER SET latin1 NOT NULL,
  `date_of_birth` date NOT NULL,
  `phone_number` varchar(15) CHARACTER SET latin1 NOT NULL,
  `current_address` varchar(255) CHARACTER SET latin1 DEFAULT NULL,
  `city` varchar(50) CHARACTER SET latin1 DEFAULT NULL,
  `province` varchar(50) CHARACTER SET latin1 DEFAULT NULL,
  `district` varchar(50) CHARACTER SET latin1 DEFAULT NULL,
  `lat` double DEFAULT NULL,
  `lng` double DEFAULT NULL,
  `job` varchar(255) CHARACTER SET latin1 DEFAULT NULL,
  `image` varchar(255) CHARACTER SET latin1 DEFAULT NULL,
  `start_income` int(10) unsigned DEFAULT NULL,
  `end_income` int(10) unsigned DEFAULT NULL,
  `interests` varchar(255) CHARACTER SET latin1 DEFAULT NULL,
  `habit` varchar(100) CHARACTER SET latin1 DEFAULT NULL,
  `is_organizer` tinyint(1) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `email` (`email`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8;